all:
	g++ SuggestAPoint.C -o SuggestAPoint.exec `root-config --glibs --cflags` -g
	g++ IsPointAcceptable.C -o IsPointAcceptable.exec `root-config --glibs --cflags` -g
	g++ StoreThisPoint.C -o StoreThisPoint.exec `root-config --glibs --cflags` -g
	g++ LogToRoot.C -o LogToRoot.exec `root-config --glibs --cflags` -g