#include <iostream>
#include <stdlib.h>

using std::endl;
using std::cout;

void CreateSuSpectInput(float pMSSMParameters[20]) {
  ofstream SusPectCard;
  SusPectCard.open("suspect2_lha.in");  
  
  SusPectCard << "# SUSY Les Houches Accord 2.0 - example input file for SUSPECT ver >= 2.4" << endl;
  SusPectCard << "Block MODSEL  # Select model (with the second parameter): " << endl;
  SusPectCard << "#            General MSSM (arbitrary soft terms) at low scale input:    0" << endl;
  SusPectCard << "#            SUGRA (!includes non-univ. soft terms, def. in block EXTPAR):  1" << endl;
  SusPectCard << "#            GMSB                                     : 2" << endl;
  SusPectCard << "#            AMSB                                    :  3" << endl;
  SusPectCard << "#            Bottom-up RGE for general MSSM input at EWSB scale: -1" << endl;
  SusPectCard << "#            (a specific SuSpect option)" << endl;
  SusPectCard << "    1    -1   #  bottom up RGE" << endl;
  SusPectCard << "#" << endl;
  SusPectCard << "Block SU_ALGO  # !Optional SUSPECT v>=2.3* block: algorithm control parameters" << endl;
  SusPectCard << "# !IF block absent (or if any parameter undefined), defaut values are taken  " << endl;
  SusPectCard << "     2    21  # 2-loop RGE (defaut, 1-loop RGE is: 11 instead)" << endl;
  SusPectCard << "     3    1   # 1: g_1(gut) = g_2(gut) consistently calculated from input" << endl;
  SusPectCard << "#   (other possibility is 0: High scale input =HIGH in block EXTPAR below)" << endl;
  SusPectCard << "     4    1   # RGE accuracy: 1: moderate, 2: accurate (but slower)  " << endl;
  SusPectCard << "     6    0   #  1: M_Hu, M_Hd input (default in constrained models)" << endl;
  SusPectCard << "#        (other possibility 0: MA_pole, MU(EWSB) input instead)" << endl;
  SusPectCard << "     7    2   #  choice for sparticles masses rad. corr. (=/= h):" << endl;
  SusPectCard << "#               2 ->all (recommended, defaut); 1->no R.C. in squarks & gauginos." << endl;
  SusPectCard << "     8    1   # 1 (defaut): EWSB scale=(mt_L*mt_R)^(1/2) " << endl;
  SusPectCard << "#         (Or = 0: arbitrary EWSB scale: give EWSB in Block EXTPAR below) " << endl;
  SusPectCard << "     9    2   # Final spectrum accuracy: 1 -> 1% acc.; 2 -> 0.01 % acc.(defaut)" << endl;
  SusPectCard << "     10   2   # Higgs boson masses rad. corr. calculation options: " << endl;
  SusPectCard << "#             A simple (but very good) approximation (advantage=fast)  : 0" << endl;
  SusPectCard << "#             Full one-loop calculation                                : 1" << endl;
  SusPectCard << "#             One-loop  + dominant DSVZ 2-loop (defaut,recommended)    : 2" << endl;
  SusPectCard << "     11   0   # Higher order Higgs 'scheme' choice in rad. corr. at mZ:" << endl;
  SusPectCard << "#          RUNNING DRbar Higgs masses at loop-level at mZ (defaut)    : 0" << endl;
  SusPectCard << "#          POLE          Higgs masses at loop-level at mZ             : 1" << endl;
  SusPectCard << "#" << endl;
  SusPectCard << "Block SMINPUTS   # Standard Model inputs (if any undefined, defaut values taken)" << endl;
  SusPectCard << "#     1     127.934  # alpha_em^(-1)(MZ) SM MSbar " << endl;
  SusPectCard << "#     2     1.16639d-5  # G_F" << endl;
  SusPectCard << "#     3      0.1172  # alpha_s(mZ) SM, MSbar" << endl;
  SusPectCard << "#     4     91.187   # mZ pole mass " << endl;
  SusPectCard << "#     5      4.25    # Mb(mb) SM MSbar" << endl;
  SusPectCard << "#     6      172.5      # Mtop(pole)" << endl;
  SusPectCard << "#     7    1.7771     # Mtau(pole)" << endl;
  SusPectCard << "#" << endl;
  SusPectCard << "Block MINPAR  # specific model input parameters" << endl;
  SusPectCard << "#   input for SUGRA models (! comment (#) all other (GMSB,AMSB) lines):" << endl;
  SusPectCard << "#     1    100.    # m0" << endl;
  SusPectCard << "#     2    250.    # m1%2" << endl;
  SusPectCard << "#     5   -100.      # A0" << endl;
  SusPectCard << "#     3    10.    # tanbeta(MZ)" << endl;
  SusPectCard << "#     4      1.0   # sign(mu)" << endl;
  SusPectCard << "#   input for GMSB models (! comment (#) all other (mSUGRA,AMSB) lines):" << endl;
  SusPectCard << "#     1    100.d3  # Lambda_susy" << endl;
  SusPectCard << "#     2    200.d3  # Lambda_mess" << endl;
  SusPectCard << "#     3    10     # tanbeta(MZ) " << endl;
  SusPectCard << "#     4    1.      # sign(MU)" << endl;
  SusPectCard << "#     5    1       # Nl_mes  " << endl;
  SusPectCard << "#     6    1       # Nq_mes  " << endl;
  SusPectCard << "#   input for AMSB models (! comment (#) all other (mSUGRA,GMSB) lines):" << endl;
  SusPectCard << "#     1    450.    # m0" << endl;
  SusPectCard << "#     2    60.d3   # M_3%2 gravitino mass" << endl;
  SusPectCard << "#     3    10.     # tanbeta(MZ)" << endl;
  SusPectCard << "#     4    1.      # sign(MU)" << endl;
  SusPectCard << "#     5    1.      # cQ  : weight of m0 for Q_L (3rd gen.) doublet " << endl;
  SusPectCard << "#     6    1.      # cuR : weight of m0 for u_R" << endl;
  SusPectCard << "#     7    1.      # cdR : weight of m0 for d_R " << endl;
  SusPectCard << "#     8    1.      # cL  : weight of m0 for L (1st, 2d gen.) doublet " << endl;
  SusPectCard << "#     9    1.      # ceR : weight of m0 for e_R (1st, 2d gen.)" << endl;
  SusPectCard << "#     10   1.      # cHu : weight of m0 for Hu " << endl;
  SusPectCard << "#     11   1.      # cHd : weight of m0 for Hd " << endl;
  SusPectCard << "#" << endl;
  SusPectCard << "Block EXTPAR  # general MSSM input (! IF uncommented, values replace MINPAR ones)" << endl;
  SusPectCard << "         0      4.65294922E+02   # EWSB_scale          " << endl;
  SusPectCard << "         1     " << pMSSMParameters[2] << "   # M_1                 " << endl;
  SusPectCard << "         2     " << pMSSMParameters[3] << "   # M_2                 " << endl;
  SusPectCard << "         3     " << pMSSMParameters[4] << "   # M_3                 " << endl;
  SusPectCard << "        11     " << pMSSMParameters[6] << "   # A_t                 " << endl;
  SusPectCard << "        12     " << pMSSMParameters[5] << "   # A_b                 " << endl;
  SusPectCard << "        13     " << pMSSMParameters[7] << "   # A_tau               " << endl;
  SusPectCard << "        14     " << pMSSMParameters[6] << "   # A_u                 " << endl;
  SusPectCard << "        15     " << pMSSMParameters[5] << "   # A_d                 " << endl;
  SusPectCard << "        16     " << pMSSMParameters[7] << "   # A_e                 " << endl;
  SusPectCard << "        23     " << pMSSMParameters[8] << "   # mu(EWSB)            " << endl;
  SusPectCard << "        26     " << pMSSMParameters[1] << "   # MA_pole                  " << endl;
  SusPectCard << "        25     " << pMSSMParameters[0] << "   # tanbeta(MZ)         " << endl;
  SusPectCard << "        31     " << pMSSMParameters[9] << "   # M_eL                " << endl;
  SusPectCard << "        32     " << pMSSMParameters[9] << "   # M_muL               " << endl;
  SusPectCard << "        33     " << pMSSMParameters[11] << "   # M_tauL              " << endl;
  SusPectCard << "        34     " << pMSSMParameters[10] << "   # M_eR                " << endl;
  SusPectCard << "        35     " << pMSSMParameters[10] << "   # M_muR               " << endl;
  SusPectCard << "        36     " << pMSSMParameters[12] << "   # M_tauR              " << endl;
  SusPectCard << "        41     " << pMSSMParameters[13] << "   # M_q1L               " << endl;
  SusPectCard << "        42     " << pMSSMParameters[13] << "   # M_q2L               " << endl;
  SusPectCard << "        43     " << pMSSMParameters[14] << "   # M_q3L               " << endl;
  SusPectCard << "        44     " << pMSSMParameters[15] << "   # M_uR                " << endl;
  SusPectCard << "        45     " << pMSSMParameters[15] << "   # M_cR                " << endl;
  SusPectCard << "        46     " << pMSSMParameters[16] << "   # M_tR                " << endl;
  SusPectCard << "        47     " << pMSSMParameters[17] << "   # M_dR                " << endl;
  SusPectCard << "        48     " << pMSSMParameters[17] << "   # M_sR                " << endl;
  SusPectCard << "        49     " << pMSSMParameters[18] << "   # M_bR                " << endl;
  SusPectCard.close();

}